Vokabeltrainer_BennyLukas/Vokabeltrainer_BennyLukas/Models/Word.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vokabeltrainer_BennyLukas.Models
{
    public class Word
    {
        public int ID { get; set; }
        public string Vocab { get; set; }
        public string Translation { get; set; }
        public string Note { get; set; }
        public DateTime? CreationDate { get; set; }
        public string Genre { get; set; }

        public Word() : this(0, "", "", "", null, "") { }
        public Word(int id, string vocab, string translation, string note, DateTime? creationDate, string genre)
        {
            this.ID = id;
            this.Vocab = vocab;
            this.Translation = translation;
            this.Note = note;
            this.CreationDate = creationDate;
            this.Genre = genre;
        }

    }
}

Vokabeltrainer_BennyLukas/Vokabeltrainer_BennyLukas/Controllers/WordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vokabeltrainer_BennyLukas.Models;
using Vokabeltrainer_BennyLukas.Models.db;
using MySql.Data.MySqlClient;
namespace Vokabeltrainer_BennyLukas.Controllers
{
    public class WordController : Controller
    {
        IRepositoryVocs repVocs;

        public ActionResult Index()
        {
            repVocs = new RepositoryVocsDB();
            repVocs.Open();

            try
            {
                return View("Index", repVocs.GetAllPublicWords());
            }
            catch (Exception)
            {
                return View("Message", new Message("Fehler", "Es ist ein Fehler aufgetreten!"));
            }
            finally
            {
                repVocs.Close();
            }
        }

        public ActionResult RegisteredUserVocablist()
        {
            repVocs = new RepositoryVocsDB();
            repVocs.Open();

            try
            {
                if (Session["loggedInUser"] != null)
                {
                    User u = (User)Session["loggedInUser"];
                    return View("RegisteredUserVocabList",repVocs.GetAllUserVocabs(u.ID));
                }

                else
                {
                    return View("Message", new Message("Fehler", "Sie müssen angemeldet sein, um Ihre persönliche Liste zu sehen!"));
                }
            }

            catch (Exception)
            {
                return View("Message", new Message("Fehler", "Es ist ein Fehler aufgetreten!"));
            }

            finally
            {
                repVocs.Close();
            }
        }

        [HttpGet]
        public ActionResult AddRegisteredUserVocab()
        {
            if (Session["loggedInUser"] != null)
            {
                Word w = new Word();
                return View(w);
            }
            else
            {
                return View("Message", new Message("Fehler", "Sie müssen angemeldet sein, um Vokabeln hinzuzufügen!"));
            }
        }

        [HttpPost]
        public ActionResult AddRegisteredUserVocab(Word wordToAdd)
        {
            if (wordToAdd != null)
            {
                ValidationForAddVocab(wordToAdd);
                if (ModelState.IsValid)
                {
                    repVocs = new RepositoryVocsDB();
                    repVocs.Open();
                    User u = (User)Session["loggedInUser"];
                    //UserVocabs uv = new UserVocabs(u.ID, wordToAdd.ID);
                    try
                    {
                        bool insertOK = repVocs.Insert(wordToAdd);
                        // die ID aus der DB-Tabelle des gerade eingefügten vokabels ermitteln
                        int lastVocabID = repVocs.GetLastVocabID();
                        // in die zwischentabelle die richtigen werte eintragen
                        UserVocabs uv = new UserVocabs(u.ID, lastVocabID);
                        bool relationOK = repVocs.InsertUserVocableRealtion(uv);

                        if (insertOK && relationOK)
                        {
                            return View("Message", new Message("Vokabel hinzufügen", "Eintrag erfolgreich!"));
                        }
                        else
                        {
                            return View("Message", new Message("Vokabel hinzufügen", "Eintrag nicht erfolgreich!"));
                        }
                    }

                    catch (MySqlException)
                    {
                        return View("Message", new Message("Datenbankfehler", "Es gibt zur Zeit ein Problem mit der Datenbank!"));
                    }

                    catch (Exception)
                    {
                        return View("Message", new Message("Allgemeiner Fehler", "Es ist ein allgemeiner Fehler aufgetreten!"));
                    }

                    finally
                    {
                        repVocs.Close();
                    }
                }

                else
                {
                    return View(wordToAdd);
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        //[HttpGet]
        //public ActionResult DeleteRegisteredUserVocab()
        //{
        //    if (Session["loggedInUser"] != null)
        //    {
        //        Word w = new Word();
        //        return View(w);
        //    }
        //    else
        //    {
        //        return View("Message", new Message("Fehler", "Sie müssen angemeldet sein, um Vokabeln zu löschen!"));
        //    }
        //}

        [HttpGet]
        public ActionResult DeleteRegisteredUserVocab(int ID)
        {
            if (ID >= 0)
            {
                repVocs = new RepositoryVocsDB();
                repVocs.Open();
                User u = (User)Session["loggedInUser"];
                try
                {
                    // remove uv entry
                    UserVocabs uv = new UserVocabs(u.ID, ID);
                    bool deleteOK = repVocs.RemoveUserVocableRelation(uv);

                    if (deleteOK)
                    {
                        return View("Message", new Message("Vokabel löschen", "Eintrag erfolgreich entfernt!"));
                    }
                    else
                    {
                        return View("Message", new Message("Vokabel löschen", "Eintrag konnte nicht entfernt werden!"));
                    }
                }

                catch (MySqlException)
                {
                    return View("Message", new Message("Datenbankfehler", "Es gibt zur Zeit ein Problem mit der Datenbank!"));
                }

                catch (Exception)
                {
                    return View("Message", new Message("Allgemeiner Fehler", "Es ist ein allgemeiner Fehler aufgetreten!"));
                }

                finally
                {
                    repVocs.Close();
                }
            }

            else
            {
                return RedirectToAction("Index");
            }
        }

        //[HttpGet]
        //public ActionResult SearchVocab()
        //{
        //    if (Session["loggedInUser"] != null)
        //    {
        //        return View("DeleteRegisteredUserVocab", new Word());
        //    }
        //    else
        //    {
        //        return View("Message", new Message("Fehler", "Sie müssen angemeldet sein, um Vokabeln zu löschen!"));
        //    }
        //}

        //[HttpPost]
        //public ActionResult SearchVocab(int ID)
        //{
        //    if(ID < 0)
        //    {
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        Word wordFromDB = new Word();

        //        return View("DeleteRegisteredUserVocab", wordFromDB);
        //    }
        //}
        

        private void ValidationForAddVocab(Word word)
        {
            if (word.Vocab == null)
            {
                ModelState.AddModelError("Vocab", "'Vokabel' ist ein Pflichtfeld!");
            }
            if (word.Translation == null)
            {
                ModelState.AddModelError("Translation", "'Übersetzung' ist ein Pflichtfeld!");
            }
            if (word.Genre == null)
            {
                ModelState.AddModelError("Genre", "'Genre' ist ein Pflichtfeld!");
            }
            if ((word.CreationDate > DateTime.Today) || (word.CreationDate == null))
            {
                ModelState.AddModelError("CreationDate", "Das angegebene Datum ist ungültig!");
            }
        }
    }
}

Vokabeltrainer_BennyLukas/Vokabeltrainer_BennyLukas/Views/Word/AddRegisteredUserVocab.cshtml
@model Vokabeltrainer_BennyLukas.Models.Word

@using Vokabeltrainer_BennyLukas.Models;
@{
    ViewBag.Title = "AddRegisteredUserVocab";
}

<h1>Vokabel hinzufügen</h1>

@Html.Partial("VocabForm")

Vokabeltrainer_BennyLukas/Vokabeltrainer_BennyLukas/Views/Word/Index.cshtml
@model List<Vokabeltrainer_BennyLukas.Models.Word>
    @using Vokabeltrainer_BennyLukas.Models;
    @{
        ViewBag.Title = "Index";
    }
<h1>Öffentliche Vokabeln</h1>

    @if ((Model != null) && (Model.Count >= 1))
    {
        <table id="tblWords">
            <thead>
                <tr>
                    <th>ID</th>
                    <th class="tblEG">Englisch</th>
                    <th class="tblEG">Deutsch</th>
                    <th>Notiz</th>
                    <th>Erstellungsdatum</th>
                    <th>Genre</th>
                </tr>
            </thead>
            <tbody>

                @foreach (Word w in Model)
                {
                <tr>
                    <td>@w.ID</td>
                    <td class="tblEG">@w.Vocab</td>
                    <td class="tblEG">@w.Translation</td>
                    <td>@w.Note</td>
                    <td>@w.CreationDate</td>
                    <td>@w.Genre</td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <span>Es sind keine Einträge vorhanden!</span>
    }
@{
    ViewBag.Title = "Index";
}

Vokabeltrainer_BennyLukas/Vokabeltrainer_BennyLukas/Views/Word/RegisteredUserVocablist.cshtml
@model List<Vokabeltrainer_BennyLukas.Models.Word>
@using Vokabeltrainer_BennyLukas.Models;
@{
    ViewBag.Title = "RegisteredUserVocablist";
}
<h1>Meine Liste</h1>

@if ((Model != null) && (Model.Count >= 1))
{
    <table id="tblWords">
        <thead>
            <tr>
                <th>ID</th>
                <th class="tblEG">Englisch</th>
                <th class="tblEG">Deutsch</th>
                <th>Notiz</th>
                <th>Erstellungsdatum</th>
                <th>Genre</th>
                <th>Optionen</th>
            </tr>
        </thead>
        <tbody>

            @foreach (Word w in Model)
            {
                <tr>
                    <td>@w.ID</td>
                    <td class="tblEG">@w.Vocab</td>
                    <td class="tblEG">@w.Translation</td>
                    <td>@w.Note</td>
                    <td>@w.CreationDate</td>
                    <td>@w.Genre</td>
                    <td>@Html.ActionLink("Löschen", "DeleteRegisteredUserVocab/"+w.ID, "Word")</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <span>Es sind keine Einträge vorhanden!</span>
}
@{
    ViewBag.Title = "RegisteredUserVocablist";
}

Vokabeltrainer_BennyLukas/Vokabeltrainer_BennyLukas/Views/Word/VocabForm.cshtml
@model Vokabeltrainer_BennyLukas.Models.Word

@using (Html.BeginForm())
{
    <table id="tableReg">
        <tbody>
            <tr>
                <td>
                    @Html.LabelFor(w => w.Vocab, "Vokabel: ")
                </td>
                <td>
                    @Html.TextBoxFor(w => w.Vocab)
                </td>
                <td>
                    @Html.ValidationMessageFor(w => w.Vocab)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(w => w.Translation, "Übersetzung: ")
                </td>
                <td>
                    @Html.TextBoxFor(w => w.Translation)
                </td>
                <td>
                    @Html.ValidationMessageFor(w => w.Translation)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(w => w.Note, "Notiz: ")
                </td>
                <td>
                    @Html.TextBoxFor(w => w.Note)
                </td>
                <td>
                    @Html.ValidationMessageFor(w => w.Note)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(w => w.CreationDate, "Datum: ")
                </td>
                <td>
                    @Html.TextBoxFor(w => w.CreationDate, new { type = "date" })
                </td>
                <td>
                    @Html.ValidationMessageFor(w => w.CreationDate)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(w => w.Genre, "Genre: ")
                </td>
                <td>
                    @Html.TextBoxFor(w => w.Genre)
                </td>
                <td>
                    @Html.ValidationMessageFor(w => w.Genre)
                </td>
            </tr>
            <tr>
                <td>
                    <input type="reset" value="Abbrechen" id="btnLoginRes" />
                </td>
                <td>
                    <input type="submit" value="Weiter" id="btnLoginSub" />
                </td>
            </tr>
        </tbody>
    </table><br /><br />
}